from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from control_plane import delivery
from control_plane.delivery import (
    DeliveryError,
    IssueDeliveryManager,
    _github_repo,
    _gitlab_merge_request_iid,
    _gitlab_merge_request_url,
    _gitlab_repository,
)
from symphony_windows.workspace import workspace_key


def _git(path: Path, *args: str) -> str:
    result = subprocess.run(["git", *args], cwd=path, check=True, capture_output=True, text=True)
    return result.stdout.strip()


async def test_prepare_local_commit_uses_issue_workspace(tmp_path: Path):
    root = tmp_path / "workspaces"
    workspace = root / workspace_key("ISSUE-001")
    workspace.mkdir(parents=True)
    _git(workspace, "init")
    _git(workspace, "config", "user.email", "test@example.com")
    _git(workspace, "config", "user.name", "Test")
    (workspace / "README.md").write_text("base\n", encoding="utf-8")
    _git(workspace, "add", "README.md")
    _git(workspace, "commit", "-m", "base")
    (workspace / "README.md").write_text("changed\n", encoding="utf-8")

    branch, commit = await IssueDeliveryManager(root).prepare_local_commit("ISSUE-001", "User detail")

    assert branch == "codex/issue-001"
    assert commit == _git(workspace, "rev-parse", "HEAD")
    assert _git(workspace, "log", "-1", "--pretty=%s") == "feat: User detail"


async def test_prepare_rejects_missing_workspace(tmp_path: Path):
    with pytest.raises(DeliveryError, match="workspace does not exist"):
        await IssueDeliveryManager(tmp_path).prepare_local_commit("ISSUE-999", "Missing")


async def test_prepare_uses_nested_repo_without_falling_through_to_parent(tmp_path: Path):
    _git(tmp_path, "init")
    root = tmp_path / "workspaces"
    repository = root / workspace_key("ISSUE-002") / "repo"
    repository.mkdir(parents=True)
    _git(repository, "init")
    _git(repository, "config", "user.email", "test@example.com")
    _git(repository, "config", "user.name", "Test")
    (repository / "README.md").write_text("base\n", encoding="utf-8")
    _git(repository, "add", "README.md")
    _git(repository, "commit", "-m", "base")
    (repository / "README.md").write_text("changed\n", encoding="utf-8")

    branch, commit = await IssueDeliveryManager(root).prepare_local_commit(
        "ISSUE-002", "Nested repository"
    )

    assert branch == "codex/issue-002"
    assert commit == _git(repository, "rev-parse", "HEAD")
    assert _git(tmp_path, "status", "--short") == "?? workspaces/"


def test_github_repository_parsing():
    assert _github_repo("git@github.com:openai/symphony.git") == "openai/symphony"
    assert _github_repo("https://github.com/openai/symphony") == "openai/symphony"
    with pytest.raises(DeliveryError):
        _github_repo("https://gitlab.com/openai/symphony")


def test_gitlab_repository_and_merge_request_parsing():
    repository = _gitlab_repository(
        "http://gitlab.example.test:9033/group/subgroup/project.git"
    )
    assert repository.api_base == "http://gitlab.example.test:9033"
    assert repository.project_path == "group/subgroup/project"
    assert (
        _gitlab_merge_request_iid(
            repository,
            "http://gitlab.example.test:9033/group/subgroup/project/-/merge_requests/42",
        )
        == 42
    )
    with pytest.raises(DeliveryError, match="does not match"):
        _gitlab_merge_request_iid(
            repository,
            "http://gitlab.example.test:9033/other/project/-/merge_requests/42",
        )
    assert (
        _gitlab_merge_request_url(
            "remote: View merge request:\n"
            "remote: https://gitlab.example.test/group/project/-/merge_requests/42\n"
        )
        == "https://gitlab.example.test/group/project/-/merge_requests/42"
    )


async def test_gitlab_merge_request_is_idempotent(tmp_path: Path, monkeypatch):
    calls: list[tuple[str, str, dict[str, object]]] = []

    async def fake_api(method, url, token, **kwargs):
        assert token == "host-side-token"
        calls.append((method, url, kwargs))
        if method == "GET":
            return []
        return {
            "web_url": "https://gitlab.example.test/group/project/-/merge_requests/7"
        }

    monkeypatch.setattr(delivery, "_gitlab_api", fake_api)

    result = await IssueDeliveryManager(
        tmp_path, gitlab_token="host-side-token"
    )._create_gitlab_merge_request(
        tmp_path,
        "https://gitlab.example.test/group/project.git",
        "master",
        "codex/issue-001",
        "User detail",
        "Generated by Symphony",
    )

    assert result.endswith("/merge_requests/7")
    assert [method for method, _url, _kwargs in calls] == ["GET", "POST"]
    assert calls[1][2]["json_body"] == {
        "source_branch": "codex/issue-001",
        "target_branch": "master",
        "title": "User detail",
        "description": "Generated by Symphony",
        "remove_source_branch": False,
    }
