from __future__ import annotations

import asyncio
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from control_plane.errors import ControlPlaneError
from symphony_windows.workflow import load_workflow
from symphony_windows.workspace import workspace_key


class DeliveryError(ControlPlaneError):
    status_code = 422
    code = "feature_delivery_failed"


@dataclass(frozen=True)
class CommandResult:
    returncode: int
    stdout: str
    stderr: str


class FeatureDeliveryManager:
    def __init__(self, workflow_path: str, *, workspace_root: Path | None = None) -> None:
        self.workflow_path = Path(workflow_path).resolve()
        self.workspace_root = (
            workspace_root.resolve()
            if workspace_root is not None
            else load_workflow(self.workflow_path).workspace.root
        )

    def workspace(self, feature_id: str) -> Path:
        return self.workspace_root / workspace_key(feature_id)

    async def prepare_local_commit(
        self, feature_id: str, title: str
    ) -> tuple[str, str]:
        workspace = self.workspace(feature_id)
        await self._require_repository(workspace)
        backup = workspace / ".symphony" / "profile-assets-backup"
        if backup.exists():
            raise DeliveryError("Agent Profile assets are still installed in the workspace")
        branch = _delivery_branch(feature_id)
        await _run("git", "checkout", "-B", branch, cwd=workspace)
        await _run(
            "git",
            "add",
            "-A",
            "--",
            ".",
            ":(exclude).agents/**",
            ":(exclude).symphony/**",
            cwd=workspace,
        )
        staged = await _run_result(
            "git", "diff", "--cached", "--quiet", cwd=workspace
        )
        if staged.returncode == 1:
            await _run(
                "git",
                "-c",
                "user.name=Fshows Symphony",
                "-c",
                "user.email=symphony@fshows.local",
                "commit",
                "-m",
                f"feat: {title}",
                cwd=workspace,
            )
        elif staged.returncode != 0:
            raise DeliveryError(_process_error(staged, "git diff --cached failed"))
        commit = (await _run("git", "rev-parse", "HEAD", cwd=workspace)).strip()
        if not re.fullmatch(r"[a-f0-9]{40}", commit):
            raise DeliveryError("local delivery commit is invalid")
        return branch, commit

    async def publish(
        self,
        feature_id: str,
        title: str,
        repository: dict[str, Any],
        branch: str,
        commit: str,
    ) -> str:
        workspace = self.workspace(feature_id)
        await self._require_repository(workspace)
        actual = (await _run("git", "rev-parse", "HEAD", cwd=workspace)).strip()
        if actual != commit:
            raise DeliveryError("Feature workspace HEAD does not match local delivery commit")
        remote_url = await _delivery_remote(repository)
        remote_name = "symphony-delivery"
        remotes = (await _run("git", "remote", cwd=workspace)).splitlines()
        if remote_name in remotes:
            await _run("git", "remote", "set-url", remote_name, remote_url, cwd=workspace)
        else:
            await _run("git", "remote", "add", remote_name, remote_url, cwd=workspace)
        await _run(
            "git",
            "push",
            "--set-upstream",
            remote_name,
            f"HEAD:refs/heads/{branch}",
            cwd=workspace,
        )
        repository_slug = _github_slug(remote_url)
        base_branch = str(repository.get("base_branch") or "main")
        body = (
            f"Automated implementation for {feature_id}.\n\n"
            f"Local commit: `{commit}`\n\n"
            "Generated by Fshows Symphony after all configured test stages passed."
        )
        created = await _run_result(
            "gh",
            "pr",
            "create",
            "--repo",
            repository_slug,
            "--base",
            base_branch,
            "--head",
            branch,
            "--title",
            title,
            "--body",
            body,
            cwd=workspace,
        )
        if created.returncode == 0:
            pull_request = created.stdout.strip().splitlines()[-1]
        else:
            pull_request = (
                await _run(
                    "gh",
                    "pr",
                    "view",
                    branch,
                    "--repo",
                    repository_slug,
                    "--json",
                    "url",
                    "--jq",
                    ".url",
                    cwd=workspace,
                )
            ).strip()
        if not pull_request.startswith("https://"):
            raise DeliveryError("GitHub CLI did not return a pull request URL")
        return pull_request

    async def verify_merged(self, pull_request: str) -> None:
        result = (
            await _run(
                "gh",
                "pr",
                "view",
                pull_request,
                "--json",
                "state",
                "--jq",
                ".state",
                cwd=self.workflow_path.parent,
            )
        ).strip()
        if result.upper() != "MERGED":
            raise DeliveryError(f"pull request is not merged (state={result or 'unknown'})")

    @staticmethod
    async def _require_repository(workspace: Path) -> None:
        if not workspace.is_dir():
            raise DeliveryError(f"Feature workspace does not exist: {workspace}")
        inside = (await _run("git", "rev-parse", "--is-inside-work-tree", cwd=workspace)).strip()
        if inside != "true":
            raise DeliveryError("Feature workspace is not a Git repository")


async def _delivery_remote(repository: dict[str, Any]) -> str:
    value = str(repository.get("url") or "").strip()
    local = Path(value)
    if local.is_absolute() and local.is_dir():
        return (await _run("git", "remote", "get-url", "origin", cwd=local)).strip()
    if not value:
        raise DeliveryError("repository URL is missing")
    return value


def _delivery_branch(feature_id: str) -> str:
    suffix = re.sub(r"[^a-z0-9._-]+", "-", feature_id.lower()).strip("-.")
    return f"codex/{suffix}"


def _github_slug(remote_url: str) -> str:
    patterns = (
        r"^https://github\.com/([^/]+/[^/]+?)(?:\.git)?$",
        r"^git@github\.com:([^/]+/[^/]+?)(?:\.git)?$",
        r"^ssh://git@github\.com/([^/]+/[^/]+?)(?:\.git)?$",
    )
    for pattern in patterns:
        match = re.fullmatch(pattern, remote_url.rstrip("/"))
        if match:
            return match.group(1)
    raise DeliveryError(f"pull request creation requires a GitHub remote: {remote_url}")


async def _run(*args: str, cwd: Path) -> str:
    result = await _run_result(*args, cwd=cwd)
    if result.returncode != 0:
        raise DeliveryError(_process_error(result, f"command failed: {' '.join(args[:3])}"))
    return result.stdout


async def _run_result(*args: str, cwd: Path) -> CommandResult:
    executable = shutil.which(args[0])
    if executable is None:
        raise DeliveryError(f"required executable is unavailable: {args[0]}")
    env = os.environ.copy()
    env["GIT_TERMINAL_PROMPT"] = "0"
    process = await asyncio.create_subprocess_exec(
        executable,
        *args[1:],
        cwd=cwd,
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=180)
    except TimeoutError as error:
        process.kill()
        await process.wait()
        raise DeliveryError(f"command timed out: {' '.join(args[:3])}") from error
    return CommandResult(
        returncode=process.returncode or 0,
        stdout=stdout.decode("utf-8", errors="replace"),
        stderr=stderr.decode("utf-8", errors="replace"),
    )


def _process_error(process: CommandResult, fallback: str) -> str:
    return (process.stderr or process.stdout).strip() or fallback
