"""initial schema

Revision ID: ee63ed53e1cc
Revises:
Create Date: 2026-08-04 00:12:01.103811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'ee63ed53e1cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_profile_version')
    )
    op.create_table('features',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('agent_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('repository', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('blocker', sa.JSON(), nullable=True),
    sa.Column('claim_worker_id', sa.String(length=200), nullable=True),
    sa.Column('claim_token_hash', sa.String(length=64), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'running' AND claim_worker_id IS NOT NULL AND claim_token_hash IS NOT NULL AND claim_expires_at IS NOT NULL) OR (status <> 'running' AND claim_worker_id IS NULL AND claim_token_hash IS NULL AND claim_expires_at IS NULL)", name='ck_work_items_claim_state'),
    sa.CheckConstraint("agent_role IN ('backend_builder', 'code_reviewer', 'solution_architect', 'test_designer', 'test_executor')", name='ck_work_items_agent_role'),
    sa.CheckConstraint("stage IN ('code_review', 'implementation', 'tech_analysis', 'test_design', 'test_execution')", name='ck_work_items_stage'),
    sa.CheckConstraint("status IN ('blocked', 'cancelled', 'done', 'draft', 'needs_human', 'ready', 'retry_queued', 'rework', 'running', 'stage_review')", name='ck_work_items_status'),
    sa.CheckConstraint('priority BETWEEN 0 AND 4', name='ck_work_items_priority'),
    sa.CheckConstraint('version >= 1', name='ck_work_items_version'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index('ix_work_items_candidate_order', ['status', 'priority', 'created_at'], unique=False)
        batch_op.create_index('ix_work_items_expired_claims', ['status', 'claim_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_feature_id'), ['feature_id'], unique=False)

    op.create_table('agent_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=200), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'attempt_number', name='uq_attempt_number')
    )
    with op.batch_alter_table('agent_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_attempts_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('human_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_decisions_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('work_item_dependencies',
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('work_item_id <> depends_on_id', name='ck_dependency_not_self'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['work_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_item_id', 'depends_on_id')
    )
    op.create_table('work_item_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_item_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_work_item_created', ['work_item_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_item_events_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('work_item_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('revision', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("direction IN ('input', 'output')", name='ck_artifact_direction'),
    sa.ForeignKeyConstraint(['created_by_attempt_id'], ['agent_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'direction', 'path', 'revision', name='uq_artifact_identity')
    )
    with op.batch_alter_table('work_item_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_item_artifacts_work_item_id'), ['work_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_item_artifacts_work_item_id'))

    op.drop_table('work_item_artifacts')
    with op.batch_alter_table('work_item_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_item_events_work_item_id'))
        batch_op.drop_index('ix_events_work_item_created')

    op.drop_table('work_item_events')
    op.drop_table('work_item_dependencies')
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_decisions_work_item_id'))

    op.drop_table('human_decisions')
    with op.batch_alter_table('agent_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_attempts_work_item_id'))

    op.drop_table('agent_attempts')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_feature_id'))
        batch_op.drop_index('ix_work_items_expired_claims')
        batch_op.drop_index('ix_work_items_candidate_order')

    op.drop_table('work_items')
    op.drop_table('features')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
